# The parameters "input", "output" and "reference" are the absolute paths. Do not include the "/" at the end of the paths.
input          : "/blue/bphl-florida/dongyibo/Dev_flaq_sc2_nf/fastqs"
output    : "/blue/bphl-florida/dongyibo/Dev_flaq_sc2_nf/output"
reference      : "/blue/bphl-florida/dongyibo/Dev_flaq_sc2_nf/reference"
primer    : "/blue/bphl-florida/dongyibo/Dev_flaq_sc2_nf/primers"
# specify if input amplicons were fragmented. If yes, the parameter setting is "frag". If no, the parameter setting is "no_frag". (default: frag)
frag : "frag"
# comma separated list of SOTCs to screen, default as "S:L452R,S:E484K"
sotc : "S:L452R,S:E484K"


